# Atividade Prática: Análise de Dados no Varejo com NumPy

In [2]:
import numpy as np

## Nível 1: Básico — Faturamento Semanal e Filtros

Análise do volume de vendas de uma única loja durante uma semana comercial.

### Passo 1: Criação do array de peças vendidas

Criação de um array unidimensional `pecas_vendidas` com o histórico diário da semana: `[150, 120, 90, 210, 300, 250, 180]`.


In [3]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])
print(pecas_vendidas)

[150 120  90 210 300 250 180]


### Passo 2: Estimativa de faturamento

Multiplicação do array por 50 (preço médio por peça). Operação vetorizada, sem laços de repetição.

In [4]:
faturamento = pecas_vendidas * 50
print(faturamento)

[ 7500  6000  4500 10500 15000 12500  9000]


### Passo 3: Identificação dos dias de pico

Máscara booleana para filtrar apenas os dias com mais de 200 peças vendidas.

In [5]:
mascara_pico = pecas_vendidas > 200
print(mascara_pico)

dias_pico = pecas_vendidas[mascara_pico]
print(dias_pico)

[False False False  True  True  True False]
[210 300 250]


## Nível 2: Intermediário — Múltiplas Filiais e Falhas de Sistema

Compilação dos dados de três filiais ao longo de quatro dias. Lojas nas linhas, dias nas colunas.

### Passo 1: Criação da matriz 2D

- Loja A: `[200, 220, np.nan, 250]` (falha no sistema no 3º dia)
- Loja B: `[150, 180, 160, 190]`
- Loja C: `[300, 310, 290, 330]`

In [6]:
vendas = np.array([
    [200, 220, np.nan, 250],
    [150, 180, 160, 190],
    [300, 310, 290, 330]
])

print(vendas)

[[200. 220.  nan 250.]
 [150. 180. 160. 190.]
 [300. 310. 290. 330.]]


### Passo 2: Total de peças por loja

Soma agregando pelas linhas (`axis=1`), ignorando o `NaN` com `np.nansum`.

In [7]:
total_por_loja = np.nansum(vendas, axis=1)
print(total_por_loja)

[ 670.  680. 1230.]


### Passo 3: Média diária geral da rede

Cálculo da média ignorando os valores `nan` com `np.nanmean`, para não contaminar o resultado.

In [8]:
print(np.nanmean(vendas))

234.54545454545453


### Passo 4: Matriz condicional com `np.where()`

Classificação de cada valor em relação à meta de 200 peças: `'Meta Atingida'` ou `'Abaixo'`.

In [9]:
status_meta = np.where(vendas >= 200, 'Meta Atingida', 'Abaixo')
print(status_meta)

[['Meta Atingida' 'Meta Atingida' 'Abaixo' 'Meta Atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta Atingida' 'Meta Atingida' 'Meta Atingida' 'Meta Atingida']]


## Nível 3: Avançado — Categorização e Destaques de Marketing

Análise do perfil de vendas e do sucesso das campanhas publicitárias.

### Passo 1: Simulação de base de clientes

Uso do gerador moderno com semente fixa para reprodutibilidade. Amostra de 50 vendas entre `['Eletrônicos', 'Roupas', 'Casa']`.

In [10]:
rng = np.random.default_rng(seed=42)
departamentos = ['Eletrônicos', 'Roupas', 'Casa']
vendas_clientes = rng.choice(departamentos, size=50)

print(vendas_clientes[:10])

['Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas' 'Casa' 'Eletrônicos'
 'Casa' 'Eletrônicos' 'Eletrônicos']


### Passo 2: Volume de vendas por departamento

Contagem de valores únicos com `np.unique(return_counts=True)`.



In [11]:
categorias, contagens = np.unique(vendas_clientes, return_counts=True)
for cat, qtd in zip(categorias, contagens):
    print(f'{cat}: {qtd} vendas')

Casa: 21 vendas
Eletrônicos: 12 vendas
Roupas: 17 vendas


### Passo 3: Identificação da campanha campeã

Uso de `np.argmax()` para obter o índice do maior faturamento entre as cinco campanhas.

In [12]:
campanhas = np.array([12000, 45000, 23000, 89000, 31000])
indice_campea = np.argmax(campanhas)

print(f'Campanha campeã: índice {indice_campea}, R$ {campanhas[indice_campea]}')

Campanha campeã: índice 3, R$ 89000


# Atividade Prática: Organização e Transformação de Dados com NumPy

In [ ]:
import numpy as np

## Nível 1: Básico — Geração de Sequências e Tipagem de Dados

Criação e padronização de vetores de dados gerados automaticamente.

### Passo 1: Dias do mês

Criação de um array representando os 30 dias de um mês de faturamento com `np.arange(1, 31)`.

In [ ]:
dias = np.arange(1, 31)
print(dias)

### Passo 2: Metas igualmente espaçadas

Simulação de 5 metas de vendas igualmente espaçadas entre 20000 e 30000 R$ com `np.linspace(20000, 30000, 5)`.

In [ ]:
metas = np.linspace(20000, 30000, 5)
print(metas)

### Passo 3: Conversão de decimais para inteiros

O estoque físico foi exportado como números decimais. Conversão direta para inteiros com `.astype(int)`.

In [ ]:
estoque_decimal = np.array([10.5, 20.1, 30.9])
estoque_inteiro = estoque_decimal.astype(int)

print(estoque_decimal)
print(estoque_inteiro)

### Passo 4: Últimos 5 dias invertidos

Captura dos últimos 5 dias do array `dias` e inversão da ordem (do mais recente para o mais antigo) com fatiamento de passo negativo `[::-1]`.

In [ ]:
ultimos_5 = dias[-5:][::-1]
print(ultimos_5)

## Nível 2: Intermediário — Redimensionamento e Proteção de Dados

Manipulação do formato (shape) das matrizes e compreensão do gerenciamento de memória durante o fatiamento.

### Passo 1: Reorganização em matriz trimestral

Array unidimensional com o total de visitas de um portal em 12 meses. Reorganização em matriz de 4 trimestres × 3 meses com `.reshape(4, 3)`.

In [ ]:
visitas_12_meses = np.arange(1000, 2200, 100)
matriz_trimestral = visitas_12_meses.reshape(4, 3)

print(matriz_trimestral)

### Passo 2: Empilhamento vertical com `np.vstack()`

Combinação dos dados do primeiro semestre (marketing) com os do segundo semestre (comercial), empilhando as matrizes verticalmente.

In [ ]:
primeiro_semestre = np.array([[1000, 1100, 1200], [1300, 1400, 1500]])
segundo_semestre  = np.array([[1600, 1700, 1800], [1900, 2000, 2100]])

ano_completo = np.vstack((primeiro_semestre, segundo_semestre))
print(ano_completo)

### Passo 3: Fatiamento seguro com `.copy()`

Extração do primeiro trimestre com `.copy()` para evitar que alterações na fatia modifiquem o array original por acidente.

In [ ]:
primeiro_trimestre = ano_completo[0, :].copy()
primeiro_trimestre[0] = 99999

print(primeiro_trimestre)
print(ano_completo[0, :])

### Passo 4: Achatamento com `.ravel()`

Achamento da matriz bidimensional de volta em um array 1D para exportar como relatório corrido.

In [ ]:
relatorio_corrido = ano_completo.ravel()
print(relatorio_corrido)

## Nível 3: Avançado — Ranking, Broadcasting e Resolução de Sistemas

Álgebra linear e manipulação de dimensões para análise de cenários.

### Passo 1: Ranking com `np.argsort()`

Pontuações de alunos em uma avaliação de pensamento computacional. Uso de `np.argsort()` para obter os índices da ordenação e descobrir a posição de cada aluno no ranking.



In [ ]:
notas = np.array([85, 92, 78, 95, 88])
indices_ordenados = np.argsort(notas)

print(indices_ordenados)

### Passo 2: Broadcasting com `np.newaxis`

Inserção de uma nova dimensão em um vetor de preços base para transformá-lo em coluna, permitindo cruzar múltiplos percentuais de desconto simultaneamente via broadcasting.

In [ ]:
precos_base = np.array([100, 200, 300, 400])
precos_coluna = precos_base[:, np.newaxis]
descontos = np.array([0.10, 0.20, 0.30])

precos_com_desconto = precos_coluna * (1 - descontos)
print(precos_com_desconto)

### Passo 3: Resolução de sistemas com `np.linalg.solve()`

Determinação do custo unitário de dois recursos de hardware.

- Projeto A: 2 placas robóticas + 1 sensor = R$ 500

- Projeto B: 1 placa robótica − 1 sensor = R$ 100

Resolução do sistema com `np.linalg.solve(A, b)`, sem cálculo manual.

In [ ]:
A = np.array([[2,  1],
              [1, -1]])
b = np.array([500, 100])

solucao = np.linalg.solve(A, b)
print(f'Placa robótica: R$ {solucao[0]:.2f}')
print(f'Sensor        : R$ {solucao[1]:.2f}')